global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"

rule_files:
  - "slo.rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    file_sd_configs:
      - files:
        - 'prometheus-targets.yml'